### ISSUE TITLE
ValueCollection.ToString() will fail with exception

### ISSUE THREAD

**Issue by karol-gro** [nemesissoft/Nemesis.Essentials#1]
In ValueCollection<T> the ToString() method causes infinite call of loops: 
```csharp
        public string ToString(string? format, IFormatProvider? formatProvider)
        {
            //TODO propose a meaningful format i.e. [,] or {;}

            return $"[{FormatValue(this, formatProvider)}]"; // Here we call FormatValue on ValueCollection
        }
        private static string? FormatValue(object? value, IFormatProvider? formatProvider) =>
            value switch
            {
                null => "∅",
                bool b => b ? "true" : "false",
                string s => $"\"{s}\"",
                char c => $"\'{c}\'",
                DateTime dt => dt.ToString("o", formatProvider),
                IFormattable @if => @if.ToString(null, formatProvider),   // Here FormatValue calls ToString back
                IEnumerable ie => "[" + string.Join(", ", ie.Cast<object>().Select(e => FormatValue(e, formatProvider))) + "]",
                _ => value.ToString()
            };
```
In order to fix it I'd suggest following change:
```csharp
public string ToString(string? format, IFormatProvider? formatProvider)
	=> "[" + string.Join(", ", this.Select(e => FormatValue(e, formatProvider))) + "]";
```
Implementation is similar to `IEnumerable` branch in `switch-case`. As for the TODO: `[...]` looks much more logical to me, as it is standard collection format in JSON and similar languages (`{...}` suggests object or dictionary)

**Comment by MichalBrylka** [comment]
Thank you for your keen eye, that was an obvious mishap. I've already fixed it and added tests for ToString()
If you are happy with this fix, please close the issue 

@qj0n 
Are you using this library from nuget package and need a new release or you just happen to spot this error in source ?

**Comment by karol-gro** [comment]
I just happened to spot this, when I implemented in my source code a read-only version of this.

Dzięki, zamykam
