### ISSUE TITLE
StackOverflowException may happen in ToString on ValueCollection

### ISSUE THREAD

**Issue by pluskal** [nemesissoft/Nemesis.Essentials#2]
In case that I have a self-referencing loop in the object hierarchy that a `ToString` is called on top-level object, I am getting a StackOverflowException.

E.g.
```
record A {
ValueCollection<B> Bs;
}

record B {
A a;
}
```

Any thoughts on how to prevent this?

Very simple loop prevention may look like this:

```
        private static string? FormatValue(object? value, IFormatProvider? formatProvider) =>
            CheckSelfReferencingLoop() ?? value switch
            {
                null => "∅",
                bool b => b ? "true" : "false",
                string s => $"\"{s}\"",
                char c => $"\'{c}\'",
                DateTime dt => dt.ToString("o", formatProvider),
                IFormattable @if => @if.ToString(null, formatProvider),
                IEnumerable ie => "[" +
                                  string.Join(", ", ie.Cast<object>().Select(e => FormatValue(e, formatProvider))) +
                                  "]",
                _ => value.ToString()
            };

        private static string? CheckSelfReferencingLoop()
        {
            StackTrace st = new(true);
            var frames = st.GetFrames();
            var currentMethod = frames[0].GetMethod();
            return frames.Skip(1).Any(stackFrame => stackFrame.GetMethod() == currentMethod) ? "## SELF REFERENCING LOOP DETECTED ##" : null;
        }
```

but it does not seem right to me.

**Comment by MichalBrylka** [comment]
hi, you are quite right, this code
``` csharp
var a = new A() { Bs = new ValueCollection<B>() };
a.Bs.Add(new B() { a = a });
a.Bs.Add(new B() { a = a });
Console.WriteLine(a.ToString());
```
will definitely crash. But the problem might lay in how ToString is then called (in addition to having real cycle)

Have a look at the following (especially pay attention to Child.PrintMembers NOT calling to Parent.ToString())
``` csharp
class Program
{
    static void Main(string[] args)
    {
        var parent = new Person("Parent", new ValueCollection<Child>());
        for (int i = 0; i < 3; i++) 
            parent.Children.Add(new Child($"Child {i}", parent));

        Console.WriteLine(parent.ToString());
    }
}

record Person(string Name, ValueCollection<Child> Children)
{
    protected virtual bool PrintMembers(StringBuilder builder)
    {
        builder.AppendLine("Parent name:" + Name);
        builder.AppendLine("Children: " + Children);
        return false;
    }
}

record Child(string Name, Person Parent)
{
    protected virtual bool PrintMembers(StringBuilder builder)
    {
        builder.Append("Child name:" + Name);
        return true;
    }
}
```

Output:
```
Person { Parent name:Parent
Children: [Child { Child name:Child 0 }, Child { Child name:Child 1 }, Child { Child name:Child 2 }]
}
```

Could you please share a real life example where you'd use such code - I mean like the one you've opened this issue with?

**Comment by pluskal** [comment]
I have hit it during debugging in this demonstration.

https://github.com/nesfit/ICS/blob/ed8663bfe12e32a92a3012c69ae8c61c97080b81/Labs/Exercise-02-after/CookBook.DAL.Tests/CookBookDbContextTests.cs#L91

I use ValueCollection in DAL to allow value comparison of entities to simplify assertion. 

Thanks for the hint with https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/records.md#printing-members-printmembers-and-tostring-methods. It is a kind of solution but it may not be obvious like in my case when dubugger crashes inside a test.

**Comment by MichalBrylka** [comment]
I checked out your branch and I do not see any problems. Tests or passing as well as calls to recipeEntity.ToString()

**Comment by pluskal** [comment]
That is the catch that is not obvious :). Try to put breakpoint on the L91. EntityFramework will add circular references in `recipeEntity` after calling `SaveChanges`.

**Comment by MichalBrylka** [comment]
For your entities (RecipeEntity, IngredientAmountEntity, IngredientEntity) I added the following code:
```csharp
protected override bool PrintMembers(StringBuilder builder)
{
      builder.Append("CLASS NAME HERE:" + Id);
      //TODO add other properties here 
      return true;
}
```
and you can continue with debugging. Actually I think records are not very good candidates for entities but that's another topic. 

If you really like I can change ValueCollection.ToString method to be extension method. Feel free to also make contribution to this repo that will solve your problem but also would retain formatting functionality for others

**Comment by pluskal** [comment]
> Actually I think records are not very good candidates for entities but that's another topic.

Point noted. It would result in some troubles in identity cache but I want it to use in disconnected scenario so I houpe it should be safe.

> If you really like I can change ValueCollection.ToString method to be extension method. 
Well, it very well depends on your intended use of `ValueCollection`. 

I see following options:
1. I can submit PR either with my proposed loop break. It may hurt performance, but `ToString` should not be on hot path.
2. You may switch implicit override of `ToString` into extension. 
3. What about remove `sealed` restriction and allow inheritance and another override of `ToString`? Or, is the `sealed` intended as an performance optimisation?
4. Let the current implementation and I will use `PrintMembers`.

What is your preference?

**Comment by MichalBrylka** [comment]
I think option 3 is best here. Sealed was not placed there for perf reasons - I'm just fun of "allow for inheritance if properly designed" approach. So I'm removing it now 

This way you can also implement your CyclicValuesCollection.ToString() (new class derived from ValueCollection) - like you wanted to do in point 1 :)

**Comment by MichalBrylka** [comment]
Changes are done on master - if they are helpful to your cause I can also make release out of that - you can consume it via nuget

**Comment by pluskal** [comment]
Thank you, it was very helpful. I'll submit a PR just to track how possible reference loop can be broken in this case.

**Comment by MichalBrylka** [comment]
I think it's safe to close this issue.
Thank you for your contribution - I'm happy to accept it 
See my comments in PR

**Comment by MichalBrylka** [comment]
thank you for your contribution. Changes are merged. Release will be published momentarily

**Comment by pluskal** [comment]
Thanks for the merge. It was my pleasure to contribute.

**Comment by MichalBrylka** [comment]
@pluskal Žádný problém! :)
